# Generated by Django 6.0.3 on 2026-03-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('senior', 'Senior'), ('junior', 'Junior')], default='junior', max_length=10),
        ),
    ]
