# Generated by Django 6.0.3 on 2026-03-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_doubt_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
