# Generated by Django 6.0.3 on 2026-03-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_resource_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
